CONFIG_FILENAME = 'licenses-deny.toml'
ROOT_MARKERS = [
    CONFIG_FILENAME,
    'pyproject.toml',
    'project.toml',
    'requirements.txt',
    'requests.txt',
]

MAPPING_PACKAGE = 'licenses_deny.data'
MAPPING_FILENAME = 'mapping.toml'


TEMPLATE_CONFIG = """# License allow/deny configuration for this project, generated by licenses-deny.
[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "PSF-2.0",
  "CC0-1.0"
]

# If a package metadata license is ambiguous, add a clarification rule
clarify = [
  # { package = "example", license = "MIT", version = "<=1.2", link = "https://example/license" },
]

# Exceptions allow additional licenses for a specific package
exceptions = [
  # { package = "example-special", allow = ["MPL-2.0"] }
]

# Banned dependencies that must not appear in the environment
[bans]
packages = [
  # { name = "leftpad", reason = "Security review failed" },
]

# Non-PyPI sources allowlist (substring match)
[sources]
allow = [
  # "git:https://github.com/example/project",
  # "file:///opt/vendor/wheels",
]
"""
