CONFIG_FILENAME = 'deny-rules.toml'
ROOT_MARKERS = [
    CONFIG_FILENAME,
    'pyproject.toml',
    'project.toml',
    'requirements.txt',
    'requests.txt',
]

MAPPING_PACKAGE = 'licenses_deny.data'
MAPPING_FILENAME = 'mapping.toml'


TEMPLATE_CONFIG = """# License allow/deny configuration for this project, generated by licenses-deny.
# More configuration options, see https://github.com/John2416/licenses-deny/blob/main/deny-rules.toml
[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "PSF-2.0",
  "CC0-1.0",
]
deny = [
  "GPL-2.0",
  "GPL-3.0",
  "LGPL-2.1",
  "LGPL-3.0",
  "AGPL-3.0",
]
unlicensed = "deny"

exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = []
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
"""
